---

- name: provision wsl environment
  hosts: localhost
  connection: local
  vars:
    wsl_user: '{{ ansible_env.LOGNAME }}'
    profile_path: '{{ lookup("pipe","wslpath $(cmd.exe /c ""echo"" ""%USERPROFILE%"")") }}/wslhome'
  tasks:
  - name: dir for wsl home created
    file: >
      path={{ profile_path }}/wslhome
      state=directory
      owner={{ wsl_user }}
      group={{ wsl_user }}
  
  - name: user home in fstab updated for bind mount in fstab
    mount: >
      path=/home/{{ wsl_user }}
      src={{ profile_path }}/wslhome
      fstype=none
      opts=bind
      state=present
    register: _mount
    become: yes
  - debug: var=_mount verbosity=1
